matrix:
  include:
    - language: java
      dist: trusty
      install: true
      jdk:
        - oraclejdk8
      script:
        - ./gradlew :runner:test
        - ./build-cli.sh && cd test_projects && ./run_test.sh

    - language: node_js
      node_js:
        - "10.15.0"
      before_script:
        - cd ui
      script:
        - yarn install && yarn test
      
